version: "3"
services:
  vue:
    build:
      context: ./docker/vue
    container_name: vuegomysql2-vue
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    environment:
      VUE_APP_API_ENDPOINT: http://localhost:8082
    command: sh -c "cd assets && yarn install && yarn serve"

  go:
    build:
      context: ./docker/go
    container_name: vuegomysql2-go
    ports:
      - 8082:8082
    volumes:
      - .:/go/src
    working_dir: /go/src/app
    tty: true
    command: /bin/bash -c "go run main.go"

  db:
    image: mysql:5.7
    container_name: vuegomysql2-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPASSWORD}
      # ここで指定した名前のDBが自動作成される
      MYSQL_DATABASE: vue-go-mysql
      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  db-data:
    driver: local
